#!/usr/bin/env bash
set -e
if [ ! -f .devenv_container_id ]; then
	./devenv_start
fi
if [ $# -eq 0 ]; then
	docker exec -it -w /lucet $(cat .devenv_container_id)  /bin/bash
else
	docker exec -it -w /lucet $(cat .devenv_container_id) $@
fi
