

LUCET_TEST_OBJECTS:= $(addprefix build/, \
	lucet_test.o \
	guest_module.o \
	host_suite.o \
	session_suite.o \
	session_hostcalls.o \
	session.o \
	entrypoint_suite.o \
	memory_suite.o \
	strcmp_suite.o \
	stack_suite.o \
	start_suite.o \
	globals_suite.o \
	)

CFLAGS:= -Wall -Werror --std=c11 -g3 -fPIC -D_GNU_SOURCE -pthread
