

LUCET_BACKTRACE_HEADERS:= $(addprefix include/, \
	lucet_backtrace.h \
	)

LUCET_BACKTRACE_OBJECTS:= $(addprefix build/, \
	lucet_backtrace.o \
	)

CFLAGS:= -Wall -Werror --std=c99 -ggdb3 -fPIC -D_GNU_SOURCE \
	-fno-omit-frame-pointer \
	-fvisibility=hidden \
	-Iinclude -pthread \
	-I../lucet-runtime-c/include

ASMFLAGS:= -g3 -fPIC \
	-fno-omit-frame-pointer \
	-fvisibility=hidden
