
BENCH_OBJECTS:= $(addprefix build/, \
	bench.o \
	)

GUESTS:= $(addprefix build/guests/, \
	nop_no_heap.so \
	nop_heap_1k.so \
	nop_heap_4k.so \
	nop_heap_16k.so \
	nop_heap_64k.so \
	nop_heap_256k.so \
	)

CFLAGS:= -O2 -Wall -Werror --std=c99 -g3 -fPIC -D_GNU_SOURCE
