

LUCET_TEST_OBJECTS:= $(addprefix build/, \
	lucet_test.o \
	guest_module.o \
	guest_fault_suite.o \
	data_segment_suite.o \
	stats_suite.o \
	features_suite.o \
	features/session.o \
	features/features_guest.o \
	context_suite.o \
	entrypoint_suite.o \
	alloc_suite.o \
	alloc_context_suite.o \
	globals_suite.o \
	)

DATA_SEGMENT_GUESTS:= $(addprefix build/data_segment/, \
	valid_data_seg.so \
	no_data_seg.so \
	no_data_seg_len.so \
	no_data_seg_info.so \
	oversize_data_segs.so \
	oversize_data_seg.so \
	)

GUEST_FAULT_GUESTS:= $(addprefix build/guest_faults/, \
	traps.so \
	hostcall_error.so \
	)

FEATURES_GUESTS:= $(addprefix build/features/, \
	hello.so \
	)

STATS_GUESTS:= $(addprefix build/stats/, \
	success.so \
	fail.so \
	)

ENTRYPOINT_GUESTS:= $(addprefix build/entrypoint/, \
	calculator.so \
	)

GLOBALS_GUESTS:= $(addprefix build/globals/, \
	internal.so \
	import.so \
	)

CFLAGS:= -Wall -Werror --std=c99 -g3 -fPIC -D_GNU_SOURCE -fvisibility=default
